package deliverytracker.entity;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

/*
 * Hub.java — Entity representing a delivery distribution center (R7).
 * Stores hub name, city and address.
 * Used as reference for package location updates e.g. "Tirana Hub".
 */
@Entity
@Table(name = "hubs")
public class Hub {

    // Primary key — auto-generated by MySQL
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String city;
    private String address;

    @OneToMany(mappedBy = "currentLocation",
            fetch = FetchType.LAZY,
            cascade = CascadeType.ALL)
    private List<Driver> drivers = new ArrayList<>();

    // Getters dhe Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getCity() { return city; }
    public void setCity(String city) { this.city = city; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }

    public List<Driver> getDrivers() { return drivers; }
    public void setDrivers(List<Driver> drivers) { this.drivers = drivers; }
}
