package deliverytracker.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "packages")
// Entity class is representing a package in the delivery system.
// <p>This class is mapped to the 'packages' table in MySQL database
// Using JPA annotations can serves as the central domain object  of the entire application.</p>
//  <p>Covers requirement R7 - JPA/ORM: JPA entity with annotations, lifecycle callbacks (@PrePersist, @PreUpdate), and a  @ManyToOne relationship with the Driver entity.
//
//R7 — JPA Lifecycle Callback: runs BEFORE first INSERT. Sets default values automatically so the caller does not need to set them manually: status = "CREATED" (starting state of every package)
//trackingCode = unique TRK + current timestamp
//createdAt and updatedAt = current time
 //
public class Package {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //Primary key — auto-generated by MySQL (AUTO_INCREMENT) and uses GenerationType.IDENTITY to let the database handle ID generation.
     //
    private Long id;
//Unique tracking code generated automatically on creation.

    private String trackingCode;
    private String senderName;
    private String recipientEmail;
    private String destination;
    private double weight;
    private String status;
    private String currentLocation;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "driver_id")
    private Driver assignedDriver;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        this.status = "CREATED";
        this.trackingCode = "TRK" + System.currentTimeMillis();
    }

     // R7 — JPA Lifecycle Callback: runs BEFORE every UPDATE.
     // Keeps updatedAt synchronized with the latest change.

    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // GETTERS AND SETTERS
    // Required by JPA — it uses reflection
    // to access fields during persistence.

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getTrackingCode() { return trackingCode; }
    public void setTrackingCode(String t) { this.trackingCode = t; }

    public String getSenderName() { return senderName; }
    public void setSenderName(String s) { this.senderName = s; }

    public String getRecipientEmail() { return recipientEmail; }
    public void setRecipientEmail(String e) { this.recipientEmail = e; }

    public String getDestination() { return destination; }
    public void setDestination(String d) { this.destination = d; }

    public double getWeight() { return weight; }
    public void setWeight(double w) { this.weight = w; }

    public String getStatus() { return status; }
    public void setStatus(String s) { this.status = s; }

    public String getCurrentLocation() { return currentLocation; }
    public void setCurrentLocation(String l) { this.currentLocation = l; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime c) { this.createdAt = c; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime u) { this.updatedAt = u; }

    public Driver getAssignedDriver() { return assignedDriver; }
    public void setAssignedDriver(Driver d) { this.assignedDriver = d; }
}